remote_theme: jamigibbs/phantom
title: "Hello, I'm Ken Matsui."
description: "I currently live in Japan and study Information Science at Ritsumeikan University."
baseurl: ""
url: "https://matken11235.github.io"
twitter_username: 'matken11235'
github_username: 'matken11235'
medium_username: 'matken11235'

# Build settings
markdown: kramdown
include: [ "_pages" ]
plugins:
  - jekyll-sitemap
  - jekyll-feed

### Phantom settings
paginate: 10
footer_text: '© 2019 Ken Matsui'
admin_name: 'Ken Matsui'
google_analytics: 'UA-120440564-1'
enable_contact: false

#### Phantom Navigation menu
enable_nav: true
nav_item:
  - { url: '/', text: 'Home' }
