theme: jekyll-theme-cayman
markdown: kramdown
include: [ "_pages" ]

title: matken11235
description: "This site is portfolio of Ken Matsui"

github:
  is_project_page: true
  repository_url: "https://github.com/matken11235"

google_analytics: UA-120440564-1
plugins:
  - jekyll-sitemap
  - jekyll-feed
