theme: jekyll-theme-cayman
markdown: kramdown
include: [ "_pages" ]

title: Ken Matsui
description: "portfolio"

github:
  is_project_page: true
  repository_url: "https://github.com/matken11235"

google_analytics: UA-120440564-1
google_verify: fc3-DNsxFB8e05DlPWEyK-kgRoMf0K74PBtIT4Jh4ys
plugins:
  - jekyll-sitemap
  - jekyll-feed
